version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:ro
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:rw
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
  api:
    image: hwansolo/stanford-linguistics-api:latest
    pull_policy: always
    restart: always
    volumes:
      - ./results:/results
      - ./public:/public
    depends_on:
      - redis
      - nginx-proxy
    environment:
      VIRTUAL_HOST: cogeto-api.stanford.edu
      VIRTUAL_PORT: 5001
      LETSENCRYPT_HOST: cogeto-api.stanford.edu
      LETSENCRYPT_EMAIL: jsolis@graycoltdevelopers.com
  worker:
    image: hwansolo/stanford-linguistics-worker:latest
    pull_policy: always
    restart: always
    depends_on:
      - redis
      - nginx-proxy
    volumes:
      - ./results:/results
      - ./public:/public
  worker-monitor:
    image: hwansolo/stanford-linguistics-worker-monitor:latest
    pull_policy: always
    restart: always
    entrypoint: flower
    command: -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
      - nginx-proxy
    environment:
      VIRTUAL_HOST: cogeto-monitor.stanford.edu
      VIRTUAL_PORT: 5555
      LETSENCRYPT_HOST: cogeto-monitor.stanford.edu
      LETSENCRYPT_EMAIL: jsolis@graycoltdevelopers.com
  cogeto-client:
    image: hwansolo/stanford-linguistics-cogeto-client:latest
    pull_policy: always
    restart: always
    environment:
      VIRTUAL_HOST: cogeto.stanford.edu
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: cogeto.stanford.edu
      LETSENCRYPT_EMAIL: jsolis@graycoltdevelopers.com
    depends_on:
      - nginx-proxy
  metrical-tree-client:
    image: hwansolo/stanford-linguistics-metrical-tree-client:latest
    pull_policy: always
    restart: always
    environment:
      VIRTUAL_HOST: metricaltree.stanford.edu
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: metricaltree.stanford.edu
      LETSENCRYPT_EMAIL: jsolis@graycoltdevelopers.com
    depends_on:
      - nginx-proxy
  redis:
    image: redis
    restart: always
